apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token-secret
  data:
    - secretKey : api-token
      remoteRef:
        key: /shared/cloudflare-api-token-secret