apiVersion: external-secrets.io/v1beta1
# apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: test-secret
  namespace: external-secrets
# spec:
#   backendType: aws-ssm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: validation-secret
  data:
    - secretKey : password
      remoteRef:
        key:  /test/parameter
    - secretKey : parameter2
      remoteRef:
        key:  /test/parameter2