authentik:
  error_reporting:
    enabled: true

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: prod
    external-dns.alpha.kubernetes.io/target: "192.168.5.31"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
  hosts:
    - host: auth.mikenabhan.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
      - auth.mikenabhan.com
      secretName: authentik

postgresql:
  enabled: true
redis:
  enabled: true