apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: stage
spec:
  acme:
    email: stage-ct@mikenabhan.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: stage-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token