apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: executor
  namespace: argo
  # annotations:
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflowtaskresults
  - workflowtemplates
  - workflows
  verbs:
  - create
  - patch
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: executor
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: executor
  namespace: argo
subjects:
- kind: ServiceAccount
  name: executor
roleRef:
  kind: Role
  name: executor
---
apiVersion: v1
kind: Secret
metadata:
  name: executor-token
  namespace: argo
  annotations:
    kubernetes.io/service-account.name: executor
type: kubernetes.io/service-account-token
