apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin
  namespace: argo
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["argoproj.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin
  namespace: argo
subjects:
- kind: ServiceAccount
  name: admin
  namespace: argo
roleRef:
  kind: ClusterRole
  name: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-token
  namespace: argo
  annotations:
    kubernetes.io/service-account.name: admin
type: kubernetes.io/service-account-token
