apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: executor
  namespace: argo
  annotations:
    workflows.argoproj.io/description: |
      Recommended minimum permissions for `k8siapi` executor.

      This executor is superseded by  the `emmisary` executor, so we do not recommend you use it anymore.
    workflows.argoproj.io/version: "< 3.4.0"
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflowtaskresults
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: executor
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: executor
  namespace: argo
subjects:
# You can specify more than one "subject"
- kind: User
  name: executor # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: executor # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: executor-token
  namespace: argo
  annotations:
    kubernetes.io/service-account.name: executor
type: kubernetes.io/service-account-token
