apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:mikenabhan/argocd.git
    targetRevision: HEAD
    path: apps/cert-manager-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager-resources