apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-infra-apps
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/mikenabhan/argocd.git
    targetRevision: HEAD
    path: cluster-infra-apps
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).  
    syncOptions:
    - CreateNamespace=true
