apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-argo-rollouts
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          environment: "dev"
  template:
    metadata:
      name: '{{name}}-argo-rollouts'
    spec:
      project: default
      destination:
        namespace: argo-rollouts
        server: '{{server}}'
      sources:
      - repoURL: https://argoproj.github.io/argo-helm
        chart: argo-rollouts
        targetRevision: 2.34.2
        helm:
          releaseName: argo-rollouts
          valueFiles:
          - $values/cluster-infra-apps/argo-rollouts/{{name}}-values.yaml
      - repoURL: https://github.com/mikenabhan/argocd.git
        targetRevision: main
        ref: values
      syncPolicy:
        automated:
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
          allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).   
        syncOptions:
        - CreateNamespace=true

