apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          environment: "dev"
  template:
    metadata:
      name: '{{name}}-external-secrets'
    spec:
      project: default
      destination:
        namespace: external-secrets
        server: '{{server}}'
      sources:
      - repoURL: https://charts.external-secrets.io
        chart: external-secrets
        targetRevision: 0.9.3
        helm:
          releaseName: external-secrets
          valueFiles:
          - $values/cluster-infra-apps/external-secrets/{{metadata.labels.cloud}}-{{metadata.labels.environment}}-values.yaml
      - repoURL: https://github.com/mikenabhan/argocd.git
        targetRevision: main
        ref: values
      syncPolicy:
        automated:
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
          allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).   
        syncOptions:
        - CreateNamespace=true

