apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-ingress-nginx
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: lke-dev
        url: https://1235be22-51d7-4de1-9caf-3d25f32b34ac.us-ord-1.linodelke.net:443
        # - cluster: engineering-prod
        #   url: https://2.4.6.8
        # - cluster: finance-preprod
        #   url: https://9.8.7.6
  template:
    metadata:
      name: '{{cluster}}-ingress-nginx'
    spec:
      project: default
      destination:
        namespace: ingress-nginx
        server: '{{url}}'
      sources:
      - repoURL: https://kubernetes.github.io/ingress-nginx
        chart: ingress-nginx
        targetRevision: 4.9.1
        helm:
          releaseName: ingress-nginx
          valueFiles:
          - $values/cluster-infra-apps/ingress-nginx/{{cluster}}-values.yaml
      - repoURL: https://github.com/mikenabhan/argocd.git
        targetRevision: main
        ref: values
      syncPolicy:
        automated:
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
          allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).   
        syncOptions:
        - CreateNamespace=true

