apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          environment: "dev"
  template:
    metadata:
      name: '{{name}}-ingress-nginx'
    spec:
      project: default
      destination:
        namespace: ingress-nginx
        server: '{{server}}'
      sources:
      - repoURL: https://kubernetes.github.io/ingress-nginx
        chart: ingress-nginx
        targetRevision: 4.9.1
        helm:
          releaseName: ingress-nginx
          valueFiles:
          - $values/cluster-infra-apps/ingress-nginx/{{metadata.labels.cloud}}-{{metadata.labels.cloud}}-{{metadata.labels.environment}}-values.yaml-values.yaml
      - repoURL: https://github.com/mikenabhan/argocd.git
        targetRevision: main
        ref: values
      syncPolicy:
        automated:
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
          allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).   
        syncOptions:
        - CreateNamespace=true

