redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  autoscaling:
    enabled: true
    minReplicas: 1

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      external-dns.alpha.kubernetes.io/target: "192.168.5.31"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: "prod"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    hosts:
    - argocd.mikenabhan.com
    tls:
    - secretName: argocd-le-cert
      hosts:
      - argocd.mikenabhan.com

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 1

applicationSet:
  replicaCount: 1

configs:
  cm:
    accounts.mike: apikey, login
  rbac:
    policy.csv: |
      g, mike, role:admin
