redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  autoscaling:
    enabled: true
    minReplicas: 1

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      external-dns.alpha.kubernetes.io/target: "192.168.5.32"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: "prod"
    hosts:
      - argocd.mikenabhan.com
    tls:
      - secretName: argocd-le-cert
        hosts:
          - argocd.mikenabhan.com

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 1

applicationSet:
  replicaCount: 1

